# _config.yml
title: My LaTeX Markdown Site
description: A site with LaTeX support using MathJax
markdown: kramdown
highlighter: rouge

# 禁用 kramdown 的数学公式引擎
kramdown:
  math_engine: nil

# 自定义 MathJax 配置来支持 $...$ 和 $$...$$
mathjax_config: |
  MathJax = {
    tex: {
      inlineMath: [['$', '$'], ['\\(', '\\)']],
      displayMath: [['$$', '$$'], ['\\[', '\\]']]
    }
  };
